"""initial schema

Revision ID: 564a1d904e05
Revises: 
Create Date: 2026-05-18 22:18:05.078691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '564a1d904e05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'trade_date')
    )
    op.create_index(op.f('ix_daily_price_code'), 'daily_price', ['code'], unique=False)
    op.create_index(op.f('ix_daily_price_trade_date'), 'daily_price', ['trade_date'], unique=False)
    op.create_table('fetch_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=50), nullable=False),
    sa.Column('fetch_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows_fetched', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_name', 'fetch_date')
    )
    op.create_table('institutional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('foreign_net', sa.Float(), nullable=False),
    sa.Column('trust_net', sa.Float(), nullable=False),
    sa.Column('dealer_net', sa.Float(), nullable=False),
    sa.Column('three_major_net', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'trade_date')
    )
    op.create_index(op.f('ix_institutional_code'), 'institutional', ['code'], unique=False)
    op.create_index(op.f('ix_institutional_trade_date'), 'institutional', ['trade_date'], unique=False)
    op.create_table('margin_trading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('margin_balance', sa.Integer(), nullable=False),
    sa.Column('margin_change', sa.Integer(), nullable=False),
    sa.Column('short_balance', sa.Integer(), nullable=False),
    sa.Column('short_change', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'trade_date')
    )
    op.create_index(op.f('ix_margin_trading_code'), 'margin_trading', ['code'], unique=False)
    op.create_index(op.f('ix_margin_trading_trade_date'), 'margin_trading', ['trade_date'], unique=False)
    op.create_table('screening_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('calc_date', sa.Date(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('bb_position', sa.Float(), nullable=False),
    sa.Column('bb_peak', sa.Float(), nullable=False),
    sa.Column('peak_date', sa.Date(), nullable=True),
    sa.Column('peak_days_ago', sa.Integer(), nullable=False),
    sa.Column('is_squeeze', sa.Boolean(), nullable=False),
    sa.Column('vol_ratio', sa.Float(), nullable=False),
    sa.Column('foreign_6d_net', sa.Float(), nullable=False),
    sa.Column('trust_6d_net', sa.Float(), nullable=False),
    sa.Column('chip_ratio_6d', sa.Float(), nullable=False),
    sa.Column('chip_ratio_12d', sa.Float(), nullable=False),
    sa.Column('margin_5d_chg', sa.Float(), nullable=False),
    sa.Column('holders_1000_chg', sa.Float(), nullable=False),
    sa.Column('rs_vs_market', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passes', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'calc_date')
    )
    op.create_index(op.f('ix_screening_result_calc_date'), 'screening_result', ['calc_date'], unique=False)
    op.create_index(op.f('ix_screening_result_code'), 'screening_result', ['code'], unique=False)
    op.create_table('shareholding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('holders_1000_lot', sa.Integer(), nullable=False),
    sa.Column('pct_1000_lot', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'report_date')
    )
    op.create_index(op.f('ix_shareholding_code'), 'shareholding', ['code'], unique=False)
    op.create_index(op.f('ix_shareholding_report_date'), 'shareholding', ['report_date'], unique=False)
    op.create_table('stock_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('capital', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_list_code'), 'stock_list', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_list_code'), table_name='stock_list')
    op.drop_table('stock_list')
    op.drop_index(op.f('ix_shareholding_report_date'), table_name='shareholding')
    op.drop_index(op.f('ix_shareholding_code'), table_name='shareholding')
    op.drop_table('shareholding')
    op.drop_index(op.f('ix_screening_result_code'), table_name='screening_result')
    op.drop_index(op.f('ix_screening_result_calc_date'), table_name='screening_result')
    op.drop_table('screening_result')
    op.drop_index(op.f('ix_margin_trading_trade_date'), table_name='margin_trading')
    op.drop_index(op.f('ix_margin_trading_code'), table_name='margin_trading')
    op.drop_table('margin_trading')
    op.drop_index(op.f('ix_institutional_trade_date'), table_name='institutional')
    op.drop_index(op.f('ix_institutional_code'), table_name='institutional')
    op.drop_table('institutional')
    op.drop_table('fetch_log')
    op.drop_index(op.f('ix_daily_price_trade_date'), table_name='daily_price')
    op.drop_index(op.f('ix_daily_price_code'), table_name='daily_price')
    op.drop_table('daily_price')
    # ### end Alembic commands ###
